### ISSUE TITLE
加值多目標計算功能

### ISSUE THREAD

**Issue by stphtan94117** [JackWoo0831/Yolov7-tracker#1]
大大好
謝謝你提供的作品，很實用
但不知道能不能多開發幾個功能，例如這個影片
[https://www.youtube.com/watch?v=XwzbFzqhF1Y](url)
可以自訂各車道計算車流量、顯示車軌跡，時速的話，可以不急著弄，我覺得可能誤差會很大
如果你需要測試demo影片，我這邊可以提供讓你測試
最後謝謝你的偉大作品

**Comment by JackWoo0831** [comment]
您好，理论上是可以的，但是我最近有点别的事，以后可能会加入这个功能，因为我们组以后可能也要做车流统计这种功能。谢谢您的肯定，敬请期待

**Comment by stphtan94117** [comment]
@JackWoo0831 請問有機會另外做一個流量統計嗎 經過一年了~
