### ISSUE TITLE
yolov10训练visdroneMOT数据集

### ISSUE THREAD

**Issue by sunshinewxx** [JackWoo0831/Yolov7-tracker#105]
你好，请问如何用改进的yolov10训练visdroneMOT数据集，并用tracker输出MOTA指标呢？

**Comment by JackWoo0831** [comment]
您好，这个需要您看明白yolo v10 的接口，只要按格式输出检测结果，和tracker的输入对的上就行了。
对于指标评测，请参见[https://github.com/JonathonLuiten/TrackEval](https://github.com/JonathonLuiten/TrackEval)或[https://github.com/JackWoo0831/Easier_To_Use_TrackEval](https://github.com/JackWoo0831/Easier_To_Use_TrackEval)
