### ISSUE TITLE
question about deepMOT

### ISSUE THREAD

**Issue by 972821054** [JackWoo0831/Yolov7-tracker#11]
Hello, thank you for your perfect work. I have a question about the code that I want to ask you. There is a data set used to train DHN in deepmot -- DHN_ Data, how do you generate the. npy file in this dataset?

I would appreciate it if you could help me!

**Comment by JackWoo0831** [comment]
The npy file and pth file are both copied from the DeepMOT repo: [https://github.com/yihongXU/deepMOT](https://github.com/yihongXU/deepMOT)

**Comment by 972821054** [comment]
@JackWoo0831 Thank you for your reply！
 I have reproduced its code before. If you directly use its DHN Pth file, is there no problem? For example, the VisDrone dataset is a multi classification problem, and it is only for pedestrians.

**Comment by JackWoo0831** [comment]
Yes there's no problem since I think the DHN is  only to used to generate  affinity matrix, and when matching, I do not consider the categories of objects.
