### ISSUE TITLE
从零开始训练自己的数据集的教程

### ISSUE THREAD

**Issue by M3OT** [JackWoo0831/Yolov7-tracker#120]
作者能否写一篇博客教程来教学一下如何利用该模型库，从零开始训练自己的数据集用于目标追踪
因为目标追踪需要训练一个检测器+re-id模型，该模型库在哪里可以利用数据集来训练用于目标跟踪的re-id模型？

**Comment by JackWoo0831** [comment]
您好，抱歉这个工作目前只能支持直接读取训练好的reid模型，您可以看OSNet或者类似的reid工作的原仓库，训练好之后在这里用。
博客会考虑写，或者会出一个视频，等我这一阵忙过去~

**Comment by M3OT** [comment]
> 您好，抱歉这个工作目前只能支持直接读取训练好的reid模型，您可以看OSNet或者类似的reid工作的原仓库，训练好之后在这里用。 博客会考虑写，或者会出一个视频，等我这一阵忙过去~

不知道您是否考虑建一个交流群，让更多研究该领域的研究人员一起探讨

**Comment by M3OT** [comment]
> 您好，抱歉这个工作目前只能支持直接读取训练好的reid模型，您可以看OSNet或者类似的reid工作的原仓库，训练好之后在这里用。 博客会考虑写，或者会出一个视频，等我这一阵忙过去~

您的意思是把训练好的re-id模型的权重文件放在指定位置就可以？

**Comment by JackWoo0831** [comment]
对的
