### ISSUE TITLE
Discussion on small objects and long-tail dataset

### ISSUE THREAD

**Issue by lpc-eol** [JackWoo0831/Yolov7-tracker#13]
感谢您的工作。
我想请教的问题刚好符合TO-DO list 的第二项，即类别不平衡及小目标问题。
就此，我想与您交流一下意见。

**Comment by JackWoo0831** [comment]
这个问题我还没有充分调研过，也非常希望与您交换意见。之前看到过一篇：Towards Resolving the Challenge of Long-tail Distribution in UAV Images for Object Detection是解决VisDrone里长尾分布的，应该主要思路是额外讨论分类器的训练。如果您想进一步交流，可以加个联系方式吗？

**Comment by lpc-eol** [comment]
你好，我的微信是:Leochoizero
