### ISSUE TITLE
yolox

### ISSUE THREAD

**Issue by Zhengzhiyang0000** [JackWoo0831/Yolov7-tracker#14]

**Comment by Zhengzhiyang0000** [comment]
作者你好，请问可以将训练好的yolox模型应用在track上吗？我尝试了一下，发现报错，在导入模型的时候出现问题，请问应该怎样修改啊
![image](https://user-images.githubusercontent.com/95676739/197381057-29ec75ce-27e1-4e60-be57-20088a0ec65c.png)
![image](https://user-images.githubusercontent.com/95676739/197381065-91a346c0-2651-4cb4-883a-3f61a2d319da.png)

**Comment by JackWoo0831** [comment]
您好 YOLOX还没试过，但是您可以参照YOLO X推理代码，看它是如何导入模型的，仿照即可
