### ISSUE TITLE
visdrone2019 Dataset是用的det还是mot部分啊？

### ISSUE THREAD

**Issue by enchanterfan** [JackWoo0831/Yolov7-tracker#19]
据我所知，visdrone2019数据集有五种类型，det、vid、sot、mot、crowd，那么我想问在这个项目中作者你是用的哪个？不知道是det还是mot。

**Comment by enchanterfan** [comment]
好了，我从visdrone文件夹下的train文件中看出来是用的mot

**Comment by JackWoo0831** [comment]
您好 是的 是mot
