### ISSUE TITLE
使用自己的视频进行跟踪测试

### ISSUE THREAD

**Issue by zimuweiming** [JackWoo0831/Yolov7-tracker#2]
哈喽，想请教一下如何使用自己的视频进行跟踪测试。按照教程运行track.py文件时，更改了第35和81行DATA_ROOT的地址（注释上写这是数据集的目录），然后就会报错AssertionError: path must be your dataset path。点开是tracker_dataloader文件中的33行报错，于是更改了第29行DATA_ROOT的地址，还是有这个报错，就觉得挺奇怪的，使用跟踪应该不需要数据集吧，望解答，感谢感谢。

**Comment by JackWoo0831** [comment]
您好！首先抱歉，这个路径读取写的是有点乱，但是跟踪是需要数据集的，需要把图片读进来然后推理。出现这个assert错误是因为路径不存在，您可以再检查一下DATA_ROOT，只要保证：TrackerLoader类中的self.image_files这个变量是图片的路径的list就可以了（例如：['dataset/sequence1/00001.jpg', 'dataset/sequence1/00002.jpg']）

**Comment by youzixpz** [comment]
直接用自己的视频测试跟踪效果还要数据集吗？我也是路径有点问题

**Comment by zimuweiming** [comment]
我也觉得很奇怪，我一直没成功。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JackWoo0831/Yolov7-tracker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月23日(星期天) 晚上9:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JackWoo0831/Yolov7-tracker] 使用自己的视频进行跟踪测试 (Issue #2)





 
直接用自己的视频测试跟踪效果还要数据集吗？我也是路径有点问题

**Comment by ahnz7** [comment]
> 直接用自己的视频测试跟踪效果还要数据集吗？我也是路径有点问题

请问可以有解决吗？如果有，能告诉我一下吗？谢谢

**Comment by charming2992** [comment]
> 直接用自己的视频测试跟踪效果还要数据集吗？我也是路径有点问题

看代码数据输入好像是需要一张一张的图片（yolo格式的txt文件），没有提供输入视频的功能

**Comment by zimuweiming** [comment]
是的，我路径也是一直有问题，而且解决不了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JackWoo0831/Yolov7-tracker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月14日(星期一) 下午4:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JackWoo0831/Yolov7-tracker] 使用自己的视频进行跟踪测试 (Issue #2)





  
直接用自己的视频测试跟踪效果还要数据集吗？我也是路径有点问题
  
看代码数据输入好像是需要一张一张的图片（yolo格式的txt文件），没有提供输入视频的功能

**Comment by JackWoo0831** [comment]
我在README更新了对路径的说明, 您的需求是输入视频跟踪而不需要数据集吗? 抱歉之前写代码没有考虑到这方面的需求, 我这几天有时间加一下.
