### ISSUE TITLE
测试

### ISSUE THREAD

**Issue by lyt31** [JackWoo0831/Yolov7-tracker#20]
你好，很感谢你的工作，让我看到了毕业的曙光！！！
下面是几个问题：1.如果我想直接用视频输入得到跟踪结果，应该做怎样的改正呢？2.另外，请问一下您使用的设备型号是什么呢，我使用的设备sort和deepsort的fps和你近似，但是uavmot几乎只有一半。（多次实验的结果）3.直接使用yolov5的tracker好像有一点问题，提示NameError: name 'DetectMultiBackend' is not defined，请问是有什么模块我没下载吗？

非常希望可以得到您的一些解答！！谢谢！！

**Comment by JackWoo0831** [comment]
1. 您需要先将视频转成图片 然后逐帧读取图片
2. 我的设备CPU是Intel(R) Xeon(R) Gold 6226R，GPU训练与推理都用的一块Tesla A100-40GB
3. 这个不应该呀 您的yolo v5的自带推理代码`val.py`里有`from models.common import DetectMultiBackend`这一行吗?
