### ISSUE TITLE
KeyError: 4.0

### ISSUE THREAD

**Issue by Oceanchy6** [JackWoo0831/Yolov7-tracker#21]
大佬你好，我在利用DeepSORT进行跟踪时，加入了--save_images进行图片保存，但是出现了报错，具体如下：
uav0000009_03358_v: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "tracker/track.py", line 339, in <module>
    main(opts)
  File "tracker/track.py", line 179, in main
    plot_img(img0, frame_id, [cur_tlwh, cur_id, cur_cls], save_dir=os.path.join(DATASET_ROOT, 'reuslt_images', seq))
  File "tracker/track.py", line 252, in plot_img
    text = f'{CATEGORY_DICT[cls]}-{id}'
KeyError: 4.0
能看一下是什么原因吗

**Comment by JackWoo0831** [comment]
您好, KeyError表示在字典中没有这个键. 请检查一下在track.py的开头那几个全大写的变量里, 确保要跟踪的类和训练的检测模型是对得上的.

**Comment by mafanhahaha** [comment]
> 您好, KeyError表示在字典中没有这个键. 请检查一下在track.py的开头那几个全大写的变量里, 确保要跟踪的类和训练的检测模型是对得上的.

您好，想问一下如果想只跟踪一个类还应该修改哪里呀，visdrone检测模型有好几个类，如果修改CATEGORY_NAMES = ['car']就会出现这个问题，字典对不上，想问一下大佬，还可以修改哪里呀

**Comment by mafanhahaha** [comment]
或者是想只显示跟踪的一个类，还应该修改哪里呀

**Comment by JackWoo0831** [comment]
您好, 抱歉现在才回复.  
如果只想显示一个类, 可以在`track.py`中的`plot_img`函数中, 可以加一个`if`判断语句, 当当前结果是要显示的类时, 才显示就可以.
只跟踪一个类需要您训练只跟踪一个类的检测网络, 并且要在`yaml`文件中把`CATEGORY_DICT`的值修改成仅一类. 注意编号往往需要从0开始.
