### ISSUE TITLE
请问您代码中的train.cache这样的cache文件是怎么生成的啊？

### ISSUE THREAD

**Issue by enchanterfan** [JackWoo0831/Yolov7-tracker#22]
因为我在跑代码时，使用train_aux.py训练时发现train.cache和val.cache文件系统提示can't open/read file: check file path/integrity.
最后会导致报AssertionError: Image Not Found /data/wujiapeng/datasets/VisDrone2019/VisDrone2019/images/VisDrone2019-MOT-train/uav0000143_02250_v/0000001.jpg
为了保持路径一致，我特意建立了/data/wujiapeng/datasets/VisDrone2019文件夹去包含VisDrone2019数据集。

**Comment by Oceanchy6** [comment]
这个好像要把之前的删除，训练的时候会自动生成

**Comment by enchanterfan** [comment]
> 这个好像要把之前的删除，训练的时候会自动生成

但是即使我删除了这个缓存，的确它会尝试自动创建这样的缓存，可是它创建的缓存数据是失败的，train.cache只有1kb大小，完全就不是正常的数据量，然后我也就在自己本地训练不起来。

**Comment by JackWoo0831** [comment]
这是yolo网络在训练的时候自动生成的, 如果您生成的不正常, 建议debug看一下他是否正确读入了数据, 确保路径都是正确的. 训练方法和yolo v7(v5)一模一样, 只是加了一个tracker

**Comment by IU-LEEJIEUN** [comment]
> 

您好，请问你解决了吗，我遇到了与您一样的问题，我更改了我所能改的所有数据路径，但应该还是有什么文件漏改了，能否帮助一下我，非常谢谢!
