### ISSUE TITLE
跟踪单个类别

### ISSUE THREAD

**Issue by mafanhahaha** [JackWoo0831/Yolov7-tracker#24]
大佬您好，想问一下如果想只跟踪一个类或者是只显示跟踪的一个类还应该修改哪里呀，visdrone检测模型有好几个类，如果修改为CATEGORY_NAMES = ['car']就会出现KeyError: 4.0这个问题，字典对不上，想问一下大佬，还应该修改哪里呀

**Comment by JackWoo0831** [comment]
您好，现在代码已经修改成从yaml文件读取配置，您应该修改一下yaml文件里的CATEGORY_DICT即可。另外您可以把报错信息完整粘贴一下吗？
