### ISSUE TITLE
TrackVideo

### ISSUE THREAD

**Issue by ANZHIQIANG** [JackWoo0831/Yolov7-tracker#25]
作者你好，咱们这个项目支持跟踪视频吗，看了一下代码好像只支持图片的跟踪，如果支持麻烦帮忙介绍一下，我也是个初学者有点搞不明白了，要是不支持视频的话那是否容易实现呢，毕竟跟踪大多数是跟踪视频的，转化成图片再输入确实不太方便，期待回复，十分感谢。

**Comment by JackWoo0831** [comment]
您好 跟踪视频容易实现，只需要将视频转换为图片就可以了。您可以查一下用OpenCV库将视频转换为图片，在模型推理前转换好，设置好路径即可。

**Comment by ANZHIQIANG** [comment]
好的，感谢回复，我去尝试下。
