### ISSUE TITLE
MOT20使用yolo格式，运行tracker报错

### ISSUE THREAD

**Issue by TeanLee** [JackWoo0831/Yolov7-tracker#26]
11.27 pull 代码，执行报错
运行命令：

python tracker/track.py --dataset yolo --data_format yolo --tracker deepsort --model_path best.pt

报错如下：
yaml.scanner.ScannerError: sequence entries are not allowed here
  in "./tracker/config_files/mot.yaml", line 24, column 21

能否列出您 mot 的 yaml 配置文件。

**Comment by JackWoo0831** [comment]
您好，我目前还没有训练MOT数据集， 所以大意了，现在我更新了`mot.yaml`文件，这个问题应该解决了
