### ISSUE TITLE
camera track

### ISSUE THREAD

**Issue by Loenmagic** [JackWoo0831/Yolov7-tracker#27]
可以调用摄像头实时跟踪吗？

**Comment by JackWoo0831** [comment]
您好, 暂时没有这个功能...

**Comment by Edward-YS** [comment]
> 您好, 暂时没有这个功能...

作者您好，现在这个功能有了吗？

**Comment by JackWoo0831** [comment]
您好，目前没有~不过修改起来也简单，您用opencv库的读取视频流的函数，和摄像头匹配上就可以，我觉得主要在`track_demo.py`的基础上改就行了
