### ISSUE TITLE
抽 pedestrain和people的部分帧训练，track.py追踪后有NaN跟负值的问题

### ISSUE THREAD

**Issue by JackerLove** [JackWoo0831/Yolov7-tracker#28]
请问yolov7-w6抽两类 pedestrain和people的部分帧图片训练，运行track.py追踪后有NaN跟负值的问题，怎么解决？

**Comment by JackWoo0831** [comment]
是VisDrone吗? 有NaN的问题是因为视频里本来就没有相应类别的目标. 我跟踪车辆, 对于只有人的序列就是会NaN, 负值是因为出现了少量的FP.
总体来说, 个别视频的NaN不会影响最终结果.

**Comment by JackerLove** [comment]
抽的VisDrone2019-MOT ，想单独做人的检测跟踪，但是不知道是不是代码我没改好
