### ISSUE TITLE
数据集处理

### ISSUE THREAD

**Issue by lebron-2016** [JackWoo0831/Yolov7-tracker#29]
您好！请问您对于VisDrone-MOT数据集中，不同视频图片大小不同是如何处理的呢？

**Comment by JackWoo0831** [comment]
您好！按照yolo网络的要求，都是统一resize到相同大小的。yolo网络有两种格式：`640 x 640`和`1280 x 1280`

**Comment by lebron-2016** [comment]
嗯嗯，请问对数据集resize操作的代码部分在哪里呢？可以参考一下吗？
