### ISSUE TITLE
Request: OCSORT

### ISSUE THREAD

**Issue by sph1n3x** [JackWoo0831/Yolov7-tracker#3]
Dear @JackWoo0831 

I have come across your repo whilst looking for MOT implementations compatible with YOLOv7. You have done an amazing job so far, keep up with the work. It's great to see current MOT implementations for YOLOv7 at one place.

Will there be an implementation for OCSORT in the near future?

How is the ByteTrack implementation built? Is it based on OCSORT + Byte?

**Comment by JackWoo0831** [comment]
Thank you for your compliment.
Ok fine, I have read OCSORT before, which is an amazing work. Next step I want to try StrongSORT, and then I will try OCSORT. Thanks!
