### ISSUE TITLE
yolov8

### ISSUE THREAD

**Issue by Zhengzhiyang0000** [JackWoo0831/Yolov7-tracker#34]
作者你好，能出一个yolov8的版本吗？我尝试加了一下，但是结果是有问题的 
![image](https://user-images.githubusercontent.com/95676739/214517831-26b070d0-aa12-4c07-b9f3-7bff001ccace.png)

**Comment by Zhengzhiyang0000** [comment]
就是出一个track_yolov8.py，感谢感谢！！！！

**Comment by JackWoo0831** [comment]
好的，之前在放假，我尽快呀

**Comment by Zhengzhiyang0000** [comment]
好的好的，谢谢

**Comment by JackWoo0831** [comment]
您好 v8已经添加完毕 您可以试一下
