### ISSUE TITLE
楼主为何会频繁出现，有时候能运行，有时候不能运行的状态

### ISSUE THREAD

**Issue by wenston123** [JackWoo0831/Yolov7-tracker#35]
Tracker file not found: /home/ubuntu/wenston/tracker/results/bytetrack_09_02_17_20/uav0000297_02761_v.txt
Traceback (most recent call last):
  File "tracker/track.py", line 368, in <module>
    main(opts, cfgs)
  File "tracker/track.py", line 218, in main
    dataset_list = [trackeval.datasets.MotChallenge2DBox(dataset_config)] if opts.dataset in ['mot', 'uavdt'] else [trackeval.datasets.VisDrone2DBox(dataset_config)]
  File "/home/ubuntu/wenston/tracker/trackeval/datasets/visdrone.py", line 124, in __init__
    raise TrackEvalException(
trackeval.utils.TrackEvalException: Tracker file not found: bytetrack_09_02_17_20//uav0000297_02761_v.txt

类似的找不到的情况，

**Comment by JackWoo0831** [comment]
您好 这是因为`config_files`的`yaml`文件中的序列和`result`中的序列有时候不一致, 我已经修复了这个问题, 强制让他们一致, 您可以再测试一下.
