### ISSUE TITLE
运行的时候，内存用完

### ISSUE THREAD

**Issue by NVRGUP** [JackWoo0831/Yolov7-tracker#36]
大佬，您好！使用tracker_demo运行自己的单个视频时，卡死两次，第三次打开控制台，发现运行的时候内存暴涨，怎么调整batch_size之类的？

**Comment by JackWoo0831** [comment]
您好! `batch_size`一直是1, 估计是我把图片放到列表里, 视频比较长, 太占内存了, 我想办法优化一下, 感谢反馈!

**Comment by JackWoo0831** [comment]
您好, 我已经优化了该代码, 现在我这里跑600帧的视频内存占用是没什么问题的, 您可以再试一下.

**Comment by NVRGUP** [comment]
感谢！
