### ISSUE TITLE
训练自己数据集的一些问题

### ISSUE THREAD

**Issue by PiBigStar5712** [JackWoo0831/Yolov7-tracker#38]
我是用yoloV5结合deepsort来进行多目标的跟踪，使用的数据集是自己的数据集。目前已经在yolo中训练完成，得到了对应我自己数据集的权重文件。但是deepsort直接调用训练完的yolo的权重进行预测的时候，目标物的id会随机变化。我想这应该是跟ReID有关系吧，因为我的数据集不是行人也不是车辆。所以我想请教你以下问题：
①我是不是应该对应我自己的数据集重新训练deepsort的ReID？
②如果我需要重新训练我自己的ReID，我应该如何制作数据集，格式是什么，如何分类？比如我跟踪的目标物都是一种类别，但是他们有很多个体，那么我的数据集中train和test都应该只有一个文件夹，然后文件夹下存放的是根据yolo标签识别后的不同目标个体裁切图像吗？
③我应该如何根据制作好的数据集重新训练我自己的ReID？
感谢你的回复

**Comment by JackWoo0831** [comment]
您好, 前一阵生病了, 才看到您的问题, 我尝试回答一下:
1. 据我所知, 如果您的目标不是行人, 那么重新训练Re-ID会提高不少效果, 因为我周围有人重新训练了车辆的Re-ID模型, 在跟踪车辆上比行人的Re-ID效果显著要强.
2. 3. 非常抱歉, 我没有自己训练过Re-ID数据集, 不过您可以参考fast-reid[JDAI](https://github.com/JDAI-CV/fast-reid)这个库, 也许它可以有训练自己数据集的指引.
