### ISSUE TITLE
请教一些问题，感谢

### ISSUE THREAD

**Issue by SEUvictor** [JackWoo0831/Yolov7-tracker#4]
您好，在查找多目标跟踪方案的时候看到了您的工作，感觉很棒很感兴趣，想学习一下然后试着用到自己的论文里。
还不太懂目标跟踪任务，有几个问题想请教一下，希望能够被解答，谢谢~
1.您是用yolov7官方提供的预训练模型，在VisDrone2019-MOT数据集上训练的吗？
2.这是只再训练了检测器yolov7呢，还是同时训练了跟踪器呢？比如bytetrack，这个跟踪器本身有需要训练学习的参数吗？
3.您提供的模型权重是只训练了10 epoch的吗？
4.weights文件夹下的DHN.pth和ckpt.t7两个权重文件是什么的呢？跟踪器的吗？

**Comment by JackWoo0831** [comment]
希望我的解答能帮助您:
1.是的, 在COCO预训练的基础上训练的
2.只训练了检测器, ByteTrack如果你不用外观提取网络的话, 就不需要. 外观提取网络我没有训练, 应该就是DeepSORT原本公布的
3.训练了大概20epochs, 但是第10轮的效果最好, 您可以重新训练, 因为我训练的时候用了yolo v7默认的参数, 感觉效果不是很好
4.DHN是DeepMOT的那个深度匈牙利网络, ckpt就是DeepSORT的Re-ID网络的权重. 关于DHN的设计您可以参考原论文.

**Comment by SEUvictor** [comment]
> 

非常感谢您的详细解答！
