### ISSUE TITLE
关于使用track_demo.py测试自定义视频的错误

### ISSUE THREAD

**Issue by lhfabc9** [JackWoo0831/Yolov7-tracker#41]
使用您的代码测试自定义视频想保存txt格式的结果却保存不了。
![@4T3@ $PY` 9K J5ESR{RT4](https://user-images.githubusercontent.com/105700982/224641967-87609b41-f6ee-4a56-af0f-7d57291a6da4.png)

**Comment by JackWoo0831** [comment]
您好 这是因为results中没有结果 您可以查看一下为什么没有结果吗

**Comment by youzixpz** [comment]
我是这样的错误
![屏幕截图 2023-03-14 123353](https://user-images.githubusercontent.com/41287125/224898636-e45e7e23-8d68-433c-b50f-acffeb07be7e.png)

**Comment by youzixpz** [comment]
track执行完  保存的视频文件没找到哦  
![屏幕截图 2023-03-14 131532](https://user-images.githubusercontent.com/41287125/224902027-8b09e11d-80c2-41cd-950d-000610651632.png)

**Comment by lhfabc9** [comment]
> 

![5ZG5E J543QKHWVM4CKCZV](https://user-images.githubusercontent.com/105700982/224908612-f05d7f4f-fc54-460e-89d5-181f96d196a6.png)
不太清楚，data_type是这样的，save_txt设置为False可以正常保存视频

**Comment by youzixpz** [comment]
save_text 在哪设置 我半天没找到

**Comment by lhfabc9** [comment]
> save_text 在哪设置 我半天没找到

track_demo.py，301行

**Comment by youzixpz** [comment]
这个是默认false
我跑的track 跑通了显示save video done但是没有找到视频在哪
   track_demo错误就是图片里那样

**Comment by lhfabc9** [comment]
> 这个是默认false 我跑的track 跑通了显示save video done但是没有找到视频在哪 track_demo错误就是图片里

那不清楚了，我的是保存在demo_result文件夹里

**Comment by youzixpz** [comment]
> 

可以把你的测试demo.mp4发我一下吗

**Comment by JackWoo0831** [comment]
@youzixpz 您好, `KeyError`的错误是因为您必须指定当前视频网络推理出的类别id和要显示的名称的关系, 在`track_demo.py`第39行, 比如类别id是0代表car, 1代表people, 则需要改成

```python
CATEGORY_DICT = {0: 'car', 1: 'people'}
```

视频没找到您顺着保存路径找一下, 在`SAVE_FOLDER\reuslt_images`文件夹下

**Comment by JackWoo0831** [comment]
@lhfabc9 您好, 保存txt那里我参数传错了, 现在已经修复

**Comment by lhfabc9** [comment]
> @lhfabc9 您好, 保存txt那里我参数传错了, 现在已经修复
好的，感谢
