### ISSUE TITLE
关于评估自己的数据集的追踪效果

### ISSUE THREAD

**Issue by Clara2333333** [JackWoo0831/Yolov7-tracker#44]
您好，可以请教一下您是怎么测出MOTA，IDS等评价指标的吗，请问我如果想利用自己的视频进行评估，计算MOTA等评价指标，是不是需要先手动对一段视频用darklabel进行标注，以mot的格式保存得到gt.txt。然后跑不同追踪器的推理源码，对同一段视频进行追踪，得到追踪结果的txt文件。最后去网上找相关代码，比较这两个txt文件，来计算MOTA之类的评价指标。请问我理解的对不对呀，我在网上查的有点凌乱，有人用github上发布的TrackEval测评价指标，有人用MOT2017数据集能直接上传到MOT challenge官网上进行测评，没有太查到说怎么测评自己数据集的。

**Comment by JackWoo0831** [comment]
您好, 我认为您的思路是对的, 就可以按照MOT数据集的格式保存gt和结果, 然后用track eval进行评测. track eval还是比较权威的.

**Comment by Clara2333333** [comment]
> 您好, 我认为您的思路是对的, 就可以按照MOT数据集的格式保存gt和结果, 然后用track eval进行评测. track eval还是比较权威的.

非常感谢您的回复，我把track eval的默认值置为了false，用了您else分支里的evaluate.py进行指标计算。但是算出来的的MOTA是负无穷，其他IDP是0，IDR是NAN这样子，指标看着很不正常。gt.txt的格式为1,1,957.87,363.14,148.51,68.27,-1,-1,-1,-1。结果的txt格式为1,1,957.87,363.14,148.51,68.27,0。请问这样的格式是不适合您的evaluate.py文件吗。前六位分别是帧数，id和四个坐标呀。请问您是觉得把track eval的默认值置为ture，然后用这种格式去评价会更好吗~

**Comment by JackWoo0831** [comment]
我的`evaluate.py`是按照JDE代码里的写的, 按道理不会出现这种情况呀... 您的四个坐标的格式是`tlbr`还是`xywh`?

**Comment by Clara2333333** [comment]
我用darklabel中的MOT格式标注的，我从网上查到的MOT格式应该是 ltwh,看着追踪输出的txt和gt.txt数值还算没有差距很大，只是id不对应，比如追踪输出有69，2，234.96，443.26，119.77，76.67，0。gt.txt里有69，0，260，435，102，90，-1，-1，-1，-1这样子。所以不太理解为啥会出现负无穷qwq

**Comment by JackWoo0831** [comment]
id不对应没有关系的 评估的时候有id匹配算法 要不建议您去用一下其他代码的评估函数，看看会不会更好一些呢

**Comment by Clara2333333** [comment]
> id不对应没有关系的 评估的时候有id匹配算法 要不建议您去用一下其他代码的评估函数，看看会不会更好一些呢

好哒~非常感谢您的回复~请问您的坐标格式时tlbr吗~

**Comment by Clara2333333** [comment]
我指标输出正常啦，非常感谢作者的分享，我的数据格式有点问题，因为是单类别追踪，我直接把ignore的部分注释就好啦，非常感谢您的耐心回复~

**Comment by JackWoo0831** [comment]
不用客气

**Comment by mystarry** [comment]
> 我指标输出正常啦，非常感谢作者的分享，我的数据格式有点问题，因为是单类别追踪，我直接把ignore的部分注释就好啦，非常感谢您的耐心回复~

你好，可以看一下修改后的代码吗？我修改之后程序可以运行但是不显示任何结果。万分感谢
