### ISSUE TITLE
关于为bytetrack引入外观特征模块

### ISSUE THREAD

**Issue by Clara2333333** [JackWoo0831/Yolov7-tracker#46]
作者您好呀，看到您在bytetrack的源码中加入了和deepsort一样的外观特征，原本的bytetrack源码似乎没有这部分。请问您加这一步是提升了最后的指标吗。我测试的好像加不加没有区别，感觉是我测试的有问题，所以来请教您，十分感谢~

**Comment by JackWoo0831** [comment]
您好, 加这一步是顺便的事情, 实际上, 从我测试的结果看, 如果跟踪车辆的话, 用跟踪行人的Re-ID网络反而会降低性能.
