### ISSUE TITLE
实验性能问题

### ISSUE THREAD

**Issue by hwanghyemin** [JackWoo0831/Yolov7-tracker#48]
您好，因为我不是中国人，所以即使中文很奇怪也请谅解。 https://ieeexplore.ieee.org/document/9915399 不是别的，而是在Visdronedataset中通过将多个tracker与YOLOX结合的结果。 为什么你的代码和这个paper不同，SORT性能最好？ 而且与这个paper相比，整体性能较低，有什么理由呢？

**Comment by JackWoo0831** [comment]
1. I tested my code on UAV dataset, but the reid model I used in DeepSORT, for example, was trained in Person-ReID dataset, which probably causes low performace in DeepSORT.
2. The performance in the table in README is for all categories in VisDrone dataset, however, most paper test their model only for five categories: `car, van, truck, bus and pedestrian`.
