### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by 2436917927** [JackWoo0831/Yolov7-tracker#5]
![image](https://user-images.githubusercontent.com/44053847/192132882-5e9dca88-66cf-4479-a12c-ac87473f81ee.png)
提示cython_bbox包没有bbox_overlaps，请问是因为我windows的问题还是因为包的版本问题，您的cython-bbox是什么版本呀

**Comment by 2436917927** [comment]
另外，请问将tracks应用到其他检测器需要怎么修改代码

**Comment by JackWoo0831** [comment]
1. 我的cython_bbox版本是0.1.3, 您的版本是?
2. 应用的话, 首先需要修改里面的路径变量, 包括track.py的和tracker_dataloader.py中的. 之后您需要在track.py读取检测结果的部分作修改, 确保跟踪器可以读取检测的目标的类别, 位置和置信度~

**Comment by 2436917927** [comment]
> 1. 我的cython_bbox版本是0.1.3, 您的版本是?
> 2. 应用的话, 首先需要修改里面的路径变量, 包括track.py的和tracker_dataloader.py中的. 之后您需要在track.py读取检测结果的部分作修改, 确保跟踪器可以读取检测的目标的类别, 位置和置信度~

我的版本也是0.1.3，好奇怪他就是没有
好的谢谢您，我修改一下试试，不过前提得是我把这个环境问题解决555~

**Comment by Edward-YS** [comment]
请问Windows系统可以跑吗？还是只能用Ubuntu 18.04跑？

**Comment by 1e12Leon** [comment]
> 请问Windows系统可以跑吗？还是只能用Ubuntu 18.04跑？

可以跑，就是配环境比linux麻烦，有点久远了我也忘记最后怎么配好的了

**Comment by Edward-YS** [comment]
![image](https://github.com/user-attachments/assets/92be515b-db6d-49be-948f-45a6a249faa0)
下这几个包一直下不好

**Comment by Edward-YS** [comment]
那你最后是在Windows上跑的还是Ubuntu 18.04上跑的？

**Comment by 1e12Leon** [comment]
> 那你最后是在Windows上跑的还是Ubuntu 18.04上跑的？

windows，下不好多找找解决方案总能解决的

**Comment by Edward-YS** [comment]
好的 你用下来这几个追踪器都可以用吗
