### ISSUE TITLE
评估自己的数据集遇到的问题

### ISSUE THREAD

**Issue by mystarry** [JackWoo0831/Yolov7-tracker#51]
我想问一下track eval是只能对行人进行评估吗？我自制的动物数据集在跟踪代码运行最后就会报错trackeval.utils.TrackEvalException: Attempted to evaluate an invalid class. Only pedestrian class is valid.
  请问有没有其他的代码可以让我进行评估呢？

**Comment by mystarry** [comment]
我尝试在mot_challenge_2d_box.py中将类别修改为我的类别，但是不起作用，依然会报如上错误

**Comment by JackWoo0831** [comment]
您好, 请问您一共分几类? 最简单的方式是不修改, 让类别就是pedestrian. 如果您想更改名字, 应该同时修改mot_challenge_2d_box.py中的`line24`与`line71`:

```Python
line24:  'CLASSES_TO_EVAL': ['pedestrian'],  # Valid: ['pedestrian']
line71:  self.valid_classes = ['pedestrian']
```
让他们一致应该就可以了

**Comment by mystarry** [comment]
我一共分了四类，但是只去跟踪其中一类Tiger，我按照您的方法将两处都改成我的类别，但依然会报错，然后我尝试将该文件中所有pedestrian替换为Tiger，依然会报错 Attempted to evaluate an invalid class. Only Tiger class is valid.

**Comment by JackWoo0831** [comment]
由于这属于TrackEval库的问题, 我这几天有空看一下, 您也可以先看看网上的这篇博客, 希望能帮到您.
[https://www.cnblogs.com/zxyfrank/p/16157136.html](https://www.cnblogs.com/zxyfrank/p/16157136.html)

**Comment by yanluoxi** [comment]
请问如何使用自己的数据集

**Comment by mystarry** [comment]
> 

你这个问题有点太大了，我不太知道怎么解释
