### ISSUE TITLE
MOTA评价指标的一点小问题

### ISSUE THREAD

**Issue by Kris-Lcq** [JackWoo0831/Yolov7-tracker#52]
作者您好，我在使用您提供的在visdrone数据集上的预训练权重进行soft tracker的时候，测试出来的MOTA是负数，请问这是正常现象吗？希望作者空闲的时候能够回复我一下，万分感谢。

**Comment by JackWoo0831** [comment]
您好! 我这里测出来不是负数, 您是用TrackEval库进行测试的吗

**Comment by Kris-Lcq** [comment]
非常感谢作者百忙之中的回复，您的回复对我十分有帮助，我是使用的track.py中的track_eval进行评测的，我再看看代码，希望能够解决问题，感谢。

**Comment by JackWoo0831** [comment]
[https://github.com/JonathonLuiten/TrackEval/issues/32](https://github.com/JonathonLuiten/TrackEval/issues/32)
TrackEval的issue里也有人遇到了这个问题，您的HOTA指标也很小吗？
TrackEval的代码写的确实有点眼花缭乱，我看这几天空余时间能不能封装一个友好一点的出来

**Comment by Kris-Lcq** [comment]
感谢



---原始邮件---
发件人: "Jiapeng ***@***.***&gt;
发送时间: 2023年4月11日(周二) 晚上9:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [JackWoo0831/Yolov7-tracker] MOTA评价指标的一点小问题 (Issue #52)




 
JonathonLuiten/TrackEval#32
 TrackEval的issue里也有人遇到了这个问题，您的HOTA指标也很小吗？
 TrackEval的代码写的确实有点眼花缭乱，我看这几天空余时间能不能封装一个友好一点的出来

**Comment by Kris-Lcq** [comment]
十分感谢作者还挂念着我的问题，不胜感激，我刚才查看了一下我的结果，我的HOTA值大多数在0到20区间徘徊，不知道这个结果是正常的吗？再次感谢作者的回复。



---原始邮件---
发件人: "Jiapeng ***@***.***&gt;
发送时间: 2023年4月11日(周二) 晚上9:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [JackWoo0831/Yolov7-tracker] MOTA评价指标的一点小问题 (Issue #52)




 
JonathonLuiten/TrackEval#32
 TrackEval的issue里也有人遇到了这个问题，您的HOTA指标也很小吗？
 TrackEval的代码写的确实有点眼花缭乱，我看这几天空余时间能不能封装一个友好一点的出来

**Comment by JackWoo0831** [comment]
这个结果确实比较低，要不您再重新训练一下？我已经搞了一个比较友好的TrackEval，我再检查一下，过一阵把代码共享一下您可以试试

**Comment by Kris-Lcq** [comment]
十分感谢作者的回复，我是拿您的预训练权重进行测试的，应该是我哪里弄错了，我再试试。当然，如果您能共享一下您新版本的trackeval，那对我的工作将会非常有帮助，再次感谢，祝好。



---原始邮件---
发件人: "Jiapeng ***@***.***&gt;
发送时间: 2023年4月12日(周三) 晚上7:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [JackWoo0831/Yolov7-tracker] MOTA评价指标的一点小问题 (Issue #52)




 
这个结果确实比较低，要不您再重新训练一下？我已经搞了一个比较友好的TrackEval，我再检查一下，过一阵把代码共享一下您可以试试

**Comment by ChiachengZhang** [comment]
你好，我和他也是相同的问题MOTA为负值，HOTA也是0-20之间

**Comment by JackWoo0831** [comment]
您好，我已经发布了新版本的trackeval，此外如果您跑的是VisDrone数据集，还是用官方的MATLAB程序评测比较好。因为TrackEval只适合单类的评测
