### ISSUE TITLE
botsort

### ISSUE THREAD

**Issue by Zhengzhiyang0000** [JackWoo0831/Yolov7-tracker#54]
你好，就是我在使用botsort时，为什么速度这么慢啊，这是正常的吗？我在2080ti上测试的。
![image](https://user-images.githubusercontent.com/95676739/231336614-468a6bba-55d6-467a-ba54-205202cc24b0.png)

**Comment by JackWoo0831** [comment]
也许是相机补偿的那部分比较慢，我这速度也挺慢的。你跑BoT-SORT的原repo速度如何？
