### ISSUE TITLE
关于detection和tracking bounding box 不一样的问题

### ISSUE THREAD

**Issue by Mewscot** [JackWoo0831/Yolov7-tracker#55]
作者您好

我是用的之前自己训练的yolov7-e6e.pt这个模型来做的tracking，但是我发现对同一个视频做tracking和detection得到的结果差距很大，detection可以检测出一些物体但是在 tracking的过程中就检测不出来，同样在tracking过程中bounding box的晃动幅度会比detection大很多，请问这些情况是正常的吗

**Comment by JackWoo0831** [comment]
这些情况不是很正常，您检查一下是不是跟踪的某些阈值调的比较高，导致加了跟踪之后漏检了？晃动幅度大发生的经常么

**Comment by Mewscot** [comment]
> 这些情况不是很正常，您检查一下是不是跟踪的某些阈值调的比较高，导致加了跟踪之后漏检了？晃动幅度大发生的经常么

小目标检测会晃动幅度很大，然后追踪那种由近到远的物体boundingbox会在物体距离较近的时候变得非常大，然后物体逐渐远离bounding box才会贴合物体，很明显就是如果我只做yolov7的detection boundingbox很完美，但是如果是做tracking就会有一些bounding box变得很奇怪

**Comment by koihoo** [comment]
> 

您好，我也碰到了同样的问题。请问你解决了吗？

**Comment by Mewscot** [comment]
> > 
> 
> 您好，我也碰到了同样的问题。请问你解决了吗？

您好，目前我还没有解决，不知道作者关于这个问题有没有什么解决办法

**Comment by JackWoo0831** [comment]
您好，我尽快修复一下这个问题，谢谢反馈！

**Comment by JackWoo0831** [comment]
您好，你们解决这个问题了么？我尝试修复了一下发现不行，是不是Kalman滤波的问题？

**Comment by Mewscot** [comment]
> 您好，你们解决这个问题了么？我尝试修复了一下发现不行，是不是Kalman滤波的问题？

您好，我觉得不是Kalman滤波的问题，我这边没有对代码进行修复，我在用另外看到的tracking代码 https://github.com/theos-ai/easy-yolov7

**Comment by JackWoo0831** [comment]
心累...刚刚换了后处理代码还是不行

**Comment by JackWoo0831** [comment]
@Mewscot 他这个代码的track部分在哪里？

**Comment by JackWoo0831** [comment]
您好，已经解决了，您在试一下
