### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by Zhengzhiyang0000** [JackWoo0831/Yolov7-tracker#57]
您好，就是我在使用最新更新的版本时，使用track_yolov5.py跟踪时，总是报错，请问你您知道是是什么问题吗？我使用yoov7的跟踪时是没有问题的。
![image](https://user-images.githubusercontent.com/95676739/236628716-00ae461d-80a8-43e3-9d3d-65d4b1095661.png)

**Comment by JackWoo0831** [comment]
您好，我尽快修复一下~

**Comment by JackWoo0831** [comment]
您好, 您试一下将`track_yolov5.py`的`line139`的`out = out[0]`删去, 即

```
out = model(img.to(device))  # model forward             
out = out[0]
```
试一下

**Comment by JackWoo0831** [comment]
上一个打错了, 是
```
out = model(img.to(device))  # model forward             

```

**Comment by Zhengzhiyang0000** [comment]
您好，可以使用了

**Comment by Zhengzhiyang0000** [comment]
您好，我有个问题，就是我看c_biou论文中，作者测试的fps，c_biou的比bytetrack算法快了很多。但是我在使用作者您复现的c_biou时，fps好像相差不大。这是正常的吗？
![image](https://user-images.githubusercontent.com/95676739/236716629-4469767a-ab2a-4593-9a19-c9f8aec1a51f.png)

**Comment by JackWoo0831** [comment]
您好，这很正常，因为他没开源，我只是按照他的描述复现的，根据硬件、数据集和trick的不同，速度不同很正常。
