### ISSUE TITLE
有关相机运动补偿的问题

### ISSUE THREAD

**Issue by Saberr7** [JackWoo0831/Yolov7-tracker#58]
大佬好，我看botsort初试化时传入的use_GMC是Fasle，我想问一下之后是在哪里设置了使用相机运动补偿。
![image](https://user-images.githubusercontent.com/66422171/236661175-c87e670b-b927-4713-9490-ad85264894c5.png)
![image](https://user-images.githubusercontent.com/66422171/236661204-310c1b08-ba26-4aea-b97a-94fccc80b6d8.png)

**Comment by JackWoo0831** [comment]
没关系，直接在这里改成True即可~
