### ISSUE TITLE
为什么用除了sort和deepsort外，其他的方法都慢的离谱，十几秒跑一张

### ISSUE THREAD

**Issue by dashanlidewa** [JackWoo0831/Yolov7-tracker#59]

**Comment by JackWoo0831** [comment]
您好，我这里没遇到过这个问题，您是什么硬件平台？我这里各种方法速度都差不多

**Comment by dashanlidewa** [comment]
我的问题，matching里面算iou的时候提示cython_box与numpy1.24不兼容，我就自己换了个函数，没有cython编译函数所以巨慢。后续降了个numpy版本就ok了



---原始邮件---
发件人: "Jiapeng ***@***.***&gt;
发送时间: 2023年5月10日(周三) 上午9:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [JackWoo0831/Yolov7-tracker] 为什么用除了sort和deepsort外，其他的方法都慢的离谱，十几秒跑一张 (Issue #59)




 
您好，我这里没遇到过这个问题，您是什么硬件平台？我这里各种方法速度都差不多

**Comment by JackWoo0831** [comment]
好的~

**Comment by kingrainfly528** [comment]
> 我的问题，matching里面算iou的时候提示cython_box与numpy1.24不兼容，我就自己换了个函数，没有cython编译函数所以巨慢。后续降了个numpy版本就ok了
> […](#)
> 
> ---原始邮件---
> 发件人: "Jiapeng ***@***.***&gt;
> 发送时间: 2023年5月10日(周三) 上午9:29
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.******@***.***&gt;;
> 主题: Re: [JackWoo0831/Yolov7-tracker] 为什么用除了sort和deepsort外，其他的方法都慢的离谱，十几秒跑一张 (Issue [#59](https://github.com/JackWoo0831/Yolov7-tracker/issues/59))
> 
> 
> 
> 
> 
> 您好，我这里没遇到过这个问题，您是什么硬件平台？我这里各种方法速度都差不多
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

请问你使用numpy版本是多少
