### ISSUE TITLE
请问怎么训练自己的weights里面的ckpt.t7和DHN.pth权重文件

### ISSUE THREAD

**Issue by polarisV0V** [JackWoo0831/Yolov7-tracker#60]

**Comment by JackWoo0831** [comment]
您好，这个我都没自己训练过，DHN.pth您可以参考DeepMOT论文的repo，Reid的模型您可以采用[OSNet](https://github.com/KaiyangZhou/deep-person-reid)，其实比DeepSORT原本的好用。

**Comment by polarisV0V** [comment]
好的，非常感谢
