### ISSUE TITLE
track.py在执行时，显存占用会一直上升

### ISSUE THREAD

**Issue by bin7777** [JackWoo0831/Yolov7-tracker#61]
你好，感谢你的工作，然而我遇到了个问题
我在执行track.py的过程中发现显存随跟踪序列的进行而增加，怀疑处理完的序列的显存是不是没有释放，如果测试的序列较多，会超出显存

**Comment by bin7777** [comment]
每执行一次out=model(img)的推理，占用显存都会增加

**Comment by bin7777** [comment]
https://blog.csdn.net/qq_44660426/article/details/129571168 没有关闭梯度记录，导致梯度积累

**Comment by yang19950411** [comment]
> https://blog.csdn.net/qq_44660426/article/details/129571168 没有关闭梯度记录，导致梯度积累

您好，遇到了相同的问题，想请教以下这段代码具体应该加到什么地方

**Comment by bin7777** [comment]
> > https://blog.csdn.net/qq_44660426/article/details/129571168 没有关闭梯度记录，导致梯度积累
> 
> 您好，遇到了相同的问题，想请教以下这段代码具体应该加到什么地方

加在了track.py  最后调用main函数之前

**Comment by yang19950411** [comment]
> https://blog.csdn.net/qq_44660426/article/details/129571168 没有关闭梯度记录，导致梯度积累



> > > https://blog.csdn.net/qq_44660426/article/details/129571168 没有关闭梯度记录，导致梯度积累
> > 
> > 
> > 您好，遇到了相同的问题，想请教以下这段代码具体应该加到什么地方
> 
> 加在了track.py 最后调用main函数之前

好的，十分感谢！！

**Comment by wei3044** [comment]
> > https://blog.csdn.net/qq_44660426/article/details/129571168 没有关闭梯度记录，导致梯度积累
> 
> > > > https://blog.csdn.net/qq_44660426/article/details/129571168 没有关闭梯度记录，导致梯度积累
> > > 
> > > 
> > > 您好，遇到了相同的问题，想请教以下这段代码具体应该加到什么地方
> > 
> > 
> > 加在了track.py 最后调用main函数之前
> 
> 好的，十分感谢！！

请问你解决了吗，我也遇到这个问题了

**Comment by wei3044** [comment]
> > > https://blog.csdn.net/qq_44660426/article/details/129571168 没有关闭梯度记录，导致梯度积累
> > 
> > 
> > 您好，遇到了相同的问题，想请教以下这段代码具体应该加到什么地方
> 
> 加在了track.py 最后调用main函数之前

大佬，请问具体是加哪个代码，求助求助
