### ISSUE TITLE
关于C-BIOU

### ISSUE THREAD

**Issue by lhfabc9** [JackWoo0831/Yolov7-tracker#62]
您好，我想问下BIOU能单独实现吗？

**Comment by JackWoo0831** [comment]
您好，单独实现指的是什么呀？

**Comment by lhfabc9** [comment]
> 您好，单独实现指的是什么呀？
我想着把缓冲区那块用到其他IoU上，现在已经实现了，谢谢您的代码。

**Comment by lhfabc9** [comment]
> 您好，请问您实现的效果好么，我也实现了一下，但是发现效果很差，单独在mot16上用C-Biou，效果也是很差。请问是不是还有啥需要更改的超参数呢？

我实现的效果也不好，这方法可能挑数据集。
