### ISSUE TITLE
关于MOT17数据集跟踪结果评估，没有出现正确结果，应该怎么解决？AssertionError

### ISSUE THREAD

**Issue by zxzprince** [JackWoo0831/Yolov7-tracker#63]
test: 11264it [25:53,  7.25it/s]
average fps: 16.538430322267015
Traceback (most recent call last):
  File "tracker/track.py", line 412, in <module>
    main(opts, cfgs)
  File "tracker/track.py", line 220, in main
    assert len(yaml_dataset_config['SEQ_INFO'].keys()) == len(seqs)
AssertionError

**Comment by JackWoo0831** [comment]
您好，这个错误是因为，您需要在`tracker/config_files/*.yaml`的`TRACK_EVAL`一栏的`SEQ_INFO`键指定您评测的序列名称和长度。为了方便，您可以直接用我的这个代码：[https://github.com/JackWoo0831/Easier_To_Use_TrackEval](https://github.com/JackWoo0831/Easier_To_Use_TrackEval)
