### ISSUE TITLE
关于混合数据集训练

### ISSUE THREAD

**Issue by yanghaibin-cool** [JackWoo0831/Yolov7-tracker#64]
博主有空能够实验混合CrowdHuman和MOT17数据集进行训练的教程吗？感谢！！！

**Comment by JackWoo0831** [comment]
您好，您是想混合训练`yolo`吗？

**Comment by yanghaibin-cool** [comment]
> 您好，您是想混合训练`yolo`吗？

是的，我希望能够混合CrowdHuman和MOT17数据集训练YOLOv7检测器，就像BYTE、OCSORT混合训练YOLOX一样。

**Comment by JackWoo0831** [comment]
因为我主要做的是车辆跟踪，所以行人跟踪的数据集用的很少，之前也想做混合数据集，这样的话如果有结果，我会联系您。您可以查看一下ByteTrack代码里的`mix_det`一类代码，看看他们是如何整合数据集的。

**Comment by yanghaibin-cool** [comment]
> 因为我主要做的是车辆跟踪，所以行人跟踪的数据集用的很少，之前也想做混合数据集，这样的话如果有结果，我会联系您。您可以查看一下ByteTrack代码里的`mix_det`一类代码，看看他们是如何整合数据集的。

好的，感谢您的回复。
