### ISSUE TITLE
英文单词拼写错误

### ISSUE THREAD

**Issue by zhengyoukai** [JackWoo0831/Yolov7-tracker#67]
在visdrone.py文件下  self.valid_classes = ['pedestrian', 'people', 'bicycle', 'car', 'van', 'truck', 'tricycle', 'awning-tricycle', 'bus', 'motor'] 这段代码pedestrian 拼写错误

**Comment by JackWoo0831** [comment]
不好意思, 大意了, 会随下一次代码更新同步修正的~
