### ISSUE TITLE
visdrone 验证问题

### ISSUE THREAD

**Issue by zhengyoukai** [JackWoo0831/Yolov7-tracker#68]
` # Evaluation is ONLY valid for pedestrian class
            if len(tracker_classes) > 0 and np.max(tracker_classes) > 1:
                raise TrackEvalException(
                    'Evaluation is only valid for pedestrian class. Non pedestrian class (%i) found in sequence %s at '
                    'timestep %i.' % (np.max(tracker_classes), raw_data['seq'], t))`
你好请问一下现在visdrone 只支持pedestrian  class 而不是10个类别吗

**Comment by JackWoo0831** [comment]
是的, 评估MOT的指标只能将所有有效类视为一类, 参见[https://github.com/JackWoo0831/Easier_To_Use_TrackEval/issues/2](https://github.com/JackWoo0831/Easier_To_Use_TrackEval/issues/2)
