### ISSUE TITLE
AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'

### ISSUE THREAD

**Issue by wangwangteam** [JackWoo0831/Yolov7-tracker#69]
我使用百度云链接中的best.pt作为检测模型， 运行tracker/track_demo.py, 报错了。。。
![image](https://github.com/JackWoo0831/Yolov7-tracker/assets/26371875/c03de866-dca2-4ab4-ac1d-f74d5d10fcc1)

**Comment by JackWoo0831** [comment]
您好, 这个是pytorch版本的问题, 您的pytorch版本太新了. 直接点进报错的部分, 把相应部分注释掉就可以啦.
