### ISSUE TITLE
autoanchor:Analyzing anchors...Killed

### ISSUE THREAD

**Issue by JackerLove** [JackWoo0831/Yolov7-tracker#7]
请问使用该代码按照您的流程训练visdrone数据集报错要怎么解决？谢谢

**Comment by JackWoo0831** [comment]
这个问题确实没有遇到过... 我这里auto anchor都是好的.
现在这个问题您解决了吗?

**Comment by JackerLove** [comment]
解决了，我是ubuntu 18.04系统，GPU 3080 10G内存，把worker 改为 0 和 batch-size 改为1 才能正常运行。
另外又遇到两个问题，运行tracker/track.py 中 deepsort 会遇到 uav0000077_00720_v:773it [01:46，8.24it/s]Error：size in bbox exist zero,（115,0,3）；还有一个问题，track.py 加 --save_videos 运行结束，没有video视频生成。请问作者有遇到吗？ 谢谢。

**Comment by JackWoo0831** [comment]
天呐，竟然有0边界框？这个我没遇到过，是训练过程中出现的吗？
另外video的问题应该已经修复，您可以再试试~
