### ISSUE TITLE
text = f'{CATEGORY_DICT[cls]}-{id}' KeyError: 3.0

### ISSUE THREAD

**Issue by likwa** [JackWoo0831/Yolov7-tracker#70]
Traceback (most recent call last):
  File "C:\Users\87701\Desktop\Yolov7-tracker-master\tracker\track_demo.py", line 344, in <module>
    main(opts)
  File "C:\Users\87701\Desktop\Yolov7-tracker-master\tracker\track_demo.py", line 160, in main
    plot_img(img0, frame_id, [cur_tlwh, cur_id, cur_cls], save_dir=os.path.join(SAVE_FOLDER, 'reuslt_images', obj_name))
  File "C:\Users\87701\Desktop\Yolov7-tracker-master\tracker\track_demo.py", line 258, in plot_img
    text = f'{CATEGORY_DICT[cls]}-{id}'
KeyError: 3.0

**Comment by wallstarhug** [comment]
你好，请问这个问题解决了吗

**Comment by likwa** [comment]
没有呀 你搞出来了吗

**Comment by wallstarhug** [comment]
> 
没有弄出来

**Comment by JackWoo0831** [comment]
这个您需要在`yaml`文件里设置您要显示的类别名称和序号，例如：
```
CATEGORY_DICT:
  0: 'pedestrain'
  1: 'people'
  2: 'bicycle'
  3: 'car'
  4: 'van'
  5: 'truck'
  6: 'tricycle'
  7: 'awning-tricycle'
  8: 'bus'
  9: 'motor'
```
如果您想快速跑通，直接将`'{CATEGORY_DICT[cls]}-{id}'`改成`'class_name-{id}'`即可

**Comment by likwa** [comment]
谢谢jeck导，为啥检测视频结果是每一帧图片呀 咋设置结果还是视频呀 jeck导

**Comment by wallstarhug** [comment]
> 谢谢jeck导，为啥检测视频结果是每一帧图片呀 咋设置结果还是视频呀 jeck导

### 想问问你这个结果保存在了哪里呀，找不到结果啊

**Comment by wallstarhug** [comment]
> 谢谢jeck导，为啥检测视频结果是每一帧图片呀 咋设置结果还是视频呀 jeck导

我的怎么都没检测出来框呢，全部都是空白的图片
