### ISSUE TITLE
你好 我试着复现了一下您的实验 但是这个eval结果是不是错误的

### ISSUE THREAD

**Issue by zhengyoukai** [JackWoo0831/Yolov7-tracker#73]
![2023-06-23 16-26-18屏幕截图](https://github.com/JackWoo0831/Yolov7-tracker/assets/48206332/04d481e8-efe9-46b6-8a52-48d9e8eb70a6)

**Comment by zhengyoukai** [comment]
请问一下 track_result.txt 里面的结果怎么测出来的  好整齐的样子

**Comment by JackWoo0831** [comment]
您好, 您这个跑的是我TrackEval的那个库么? 如果真值和结果都是完全一样的内容的话, 理论上就应该都是100.

**Comment by JackWoo0831** [comment]
结果都是跟踪器自动生成的

**Comment by zhengyoukai** [comment]
> 

使用trackeval评估的吗

**Comment by JackWoo0831** [comment]
对 是用TrackEval评估的
