### ISSUE TITLE
将yolov7训练出来的best.pt用于track.py，一运行就爆显存

### ISSUE THREAD

**Issue by wallstarhug** [JackWoo0831/Yolov7-tracker#75]
请问怎么处理呢

**Comment by JackWoo0831** [comment]
您是什么显卡？

**Comment by wallstarhug** [comment]
> 您是什么显卡？

我是3080,10G显存

**Comment by wallstarhug** [comment]
> 您是什么显卡？

我在3080，10G显卡的Ubuntu系统上不会爆显存，但是在Ubuntu上运行将visdrone转换成YOLO格式的文件之后，训练的时候总提示有很多图片已经损坏，在windows系统上就不会有很多图片损坏。

**Comment by JackWoo0831** [comment]
已经损坏? 是yolo训练的时候提示标签冲突吗? 您可以把所有生成的图片和标签删除, 重新转换格式看一下

**Comment by JackWoo0831** [comment]
爆显存您可以尝试用一下yolo v7更小的模型

**Comment by wallstarhug** [comment]
> 爆显存您可以尝试用一下yolo v7更小的模型

好的，非常感谢您的回复，可是我一直用的YOLOv7的模型去做实验的（手动大哭）

**Comment by wei3044** [comment]
同问爆显存如何处理
