### ISSUE TITLE
请问visdrone（tracking）数据集训练之后0.5mAp大概是多少

### ISSUE THREAD

**Issue by wallstarhug** [JackWoo0831/Yolov7-tracker#78]
我训练出来是不到0.35，在网上没有找到使用visdrone（tracking数据集，不是detect数据集）数据集训练的，所以想请教博主，您训练出来的大概多少呢

**Comment by JackWoo0831** [comment]
您训练一共多少类? VisDrone官方指定五类: `pedestrian car van truck bus`, 如果只是这五类的话, mAP@0.5大改能有个50+
