### ISSUE TITLE
自己训练的权重识别不了？

### ISSUE THREAD

**Issue by YangBo0411** [JackWoo0831/Yolov7-tracker#79]
您好，想请问下如果我针对自己的数据集（飞机识别），利用YOLOv7训练得到了相应的权重（best.pt），现在我想利用自己训练的权重来跟踪视频中的飞机，该如何设置？
![image](https://github.com/JackWoo0831/Yolov7-tracker/assets/88123195/2687b7c9-8cca-48e3-a770-43d48a7660bf)
zhe'yi这一部分需要改成自己的数据集吗？

**Comment by JackWoo0831** [comment]
是的, 需要改成自己的数据集, 您最好已经将数据集整理成yolo格式, 并且生成了路径的txt, 这样tracker就能直接通过txt定位了
