### ISSUE TITLE
about StrongSORT

### ISSUE THREAD

**Issue by Mickeyyyang** [JackWoo0831/Yolov7-tracker#8]
Looking forward to joining StrongSORT...
Best wishes

**Comment by JackWoo0831** [comment]
By now I found that the ECC algorithm seriously slows down the speed(but use ORB and SIFT will be better as BoT-SORT), and when I use OSNet as Re-ID model, the result becomes worse. It could be the following reasons:

1. In VisDrone dataset, the Re-ID model need to be retrained
2. I didn't use cascade matching strategy as origin StrongSORT and DeepSORT did. But regardless of this, other algorithm performs better even use my simple matching strategy.
