### ISSUE TITLE
Error：size in bbox exist zero,（115,0,3）；--save_videos 运行结束没有video视频生成

### ISSUE THREAD

**Issue by JackerLove** [JackWoo0831/Yolov7-tracker#9]
运行tracker/track.py 中 deepsort 会遇到 uav0000077_00720_v:773it [01:46，8.24it/s]Error：size in bbox exist zero,（115,0,3）；还有一个问题，track.py 加 --save_videos 运行结束，没有video视频生成。请问作者有遇到吗？ 谢谢。

**Comment by mystarry** [comment]
size in bbox exist zero,（115,0,3）出现这个问题可能是使用的权重有问题，我换了一个权重就不报错了
