### ISSUE TITLE
运行yolov5跟踪问题

### ISSUE THREAD

**Issue by PiggyGaGa** [JackWoo0831/Yolov7-tracker#95]
你好，我尝试用我训练好的Yolov5模型实现运行tracker/track_yolov5.py  我理解的是直接把模型路径替换为我训练好的yolov5模型即可，但是在运行的过程中，提示我DetectMultiBackend这个函数不存在，我看代码的import，该函数应该是在models/common.py 中实现的，但在models/common.py中并没有找到这个函数，请求帮忙，是不是我的操作存在问题，或者理解的有偏差，感谢

**Comment by JackWoo0831** [comment]
您好! 我感觉这种问题是因为yolo v5的版本不同导致的. yolo v5有很多版本, 我印象里我当时训练的时候用的是v6.0

**Comment by PiggyGaGa** [comment]
@JackWoo0831 感谢，我明白怎么回事了，是我的理解有误，该仓库默认是yolov7为前端的各种tracker，所以models文件夹utils文件夹的代码不适用yolov5, 我应该把该仓库的tracker文件夹复制到yolov5官方的仓库里，然后再执行跟踪代码，就能调用我yolov5训练好的模型了。

**Comment by JackWoo0831** [comment]
您好! 好的, 祝一切顺利
